import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Nav from "@/ui/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <div className="flex h-full flex-col px-3 py-4 md:px-2">
              <Link
                className="mb-2 flex h-16 items-end justify-start rounded-md bg-gray-800 p-4 md:h-24"
                href="/"
              >
                <div className="w-32 text-white md:w-40">
                  <h4 className="text-2xl font-extrabold">Dashboard SDK</h4>
                </div>
              </Link>
              <div className="flex grow flex-row justify-between space-x-2 md:flex-col md:space-x-0">
                <Nav />
                <div className="hidden h-auto w-full grow rounded-md bg-gray-50 md:block"></div>
              </div>
            </div>
          </div>
          <div className="flex-grow p-3 md:overflow-y-auto md:p-6">
            {/* <div className="border">
              <div className="flex justify-between h-16 items-center px-4">
                <Link href={"/dashboard-example"}></Link>
              </div>
            </div> */}
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
